namespace Veil.Services;

internal sealed record LocalSpeechModelDefinition(
    string Id,
    string Family,
    string DisplayName,
    string Description,
    string StorageName,
    string DownloadUrl,
    string Sha256,
    int SizeMb,
    string SpeedLabel,
    string AccuracyLabel,
    string LanguagesLabel,
    bool SupportsTranslation,
    bool SupportsLanguageSelection,
    bool IsRecommended,
    bool IsArchive,
    string OutputStyle);

internal static class LocalSpeechModelCatalog
{
    internal const string DefaultModelId = "parakeet-tdt-0.6b-v3";

    private static readonly IReadOnlyList<LocalSpeechModelDefinition> _models =
    [
        new(
            "parakeet-tdt-0.6b-v3",
            "Parakeet",
            "Parakeet V3",
            "Fast and accurate. Recommended for most users across western languages.",
            "parakeet-tdt-0.6b-v3-int8",
            "https://blob.handy.computer/parakeet-v3-int8.tar.gz",
            "43d37191602727524a7d8c6da0eef11c4ba24320f5b4730f1a2497befc2efa77",
            478,
            "Fast",
            "High",
            "25 European languages",
            false,
            false,
            true,
            true,
            "Numbers are written as words."),
        new(
            "parakeet-tdt-0.6b-v2",
            "Parakeet",
            "Parakeet V2",
            "Fast and accurate. Optimized for English-only local transcription.",
            "parakeet-tdt-0.6b-v2-int8",
            "https://blob.handy.computer/parakeet-v2-int8.tar.gz",
            "ac9b9429984dd565b25097337a887bb7f0f8ac393573661c651f0e7d31563991",
            473,
            "Fast",
            "High",
            "English only",
            false,
            false,
            false,
            true,
            "Numbers are written as words."),
        new(
            "small",
            "Whisper",
            "Whisper Small",
            "Fast multilingual transcription with optional translation to English.",
            "ggml-small.bin",
            "https://blob.handy.computer/ggml-small.bin",
            "1be3a9b2063867b937e64e2ec7483364a79917e157fa98c5d94b5c1fffea987b",
            487,
            "Fast",
            "Good",
            "99+ languages",
            true,
            true,
            false,
            false,
            "Numbers are written as digits."),
        new(
            "medium",
            "Whisper",
            "Whisper Medium",
            "Better multilingual accuracy with a moderate speed hit.",
            "whisper-medium-q4_1.bin",
            "https://blob.handy.computer/whisper-medium-q4_1.bin",
            "79283fc1f9fe12ca3248543fbd54b73292164d8df5a16e095e2bceeaaabddf57",
            492,
            "Moderate",
            "Better",
            "99+ languages",
            true,
            true,
            false,
            false,
            "Numbers are written as digits."),
        new(
            "large",
            "Whisper",
            "Whisper Large",
            "Best Whisper accuracy with the slowest local runtime.",
            "ggml-large-v3-q5_0.bin",
            "https://blob.handy.computer/ggml-large-v3-q5_0.bin",
            "d75795ecff3f83b5faa89d1900604ad8c780abd5739fae406de19f23ecd98ad1",
            1100,
            "Slower",
            "Best",
            "99+ languages",
            true,
            true,
            false,
            false,
            "Numbers are written as digits."),
        new(
            "turbo",
            "Whisper",
            "Whisper Turbo",
            "High multilingual quality with no translation support.",
            "ggml-large-v3-turbo.bin",
            "https://blob.handy.computer/ggml-large-v3-turbo.bin",
            "1fc70f774d38eb169993ac391eea357ef47c88757ef72ee5943879b7e8e2bc69",
            1600,
            "Moderate",
            "High",
            "99+ languages",
            false,
            true,
            false,
            false,
            "Numbers are written as digits."),
        new(
            "breeze-asr",
            "Breeze ASR",
            "Breeze ASR",
            "Whisper variant optimized for Taiwanese Mandarin with code-switching support.",
            "breeze-asr-q5_k.bin",
            "https://blob.handy.computer/breeze-asr-q5_k.bin",
            "8efbf0ce8a3f50fe332b7617da787fb81354b358c288b008d3bdef8359df64c6",
            1100,
            "Moderate",
            "High",
            "Taiwanese Mandarin",
            false,
            true,
            false,
            false,
            "Numbers are written as digits."),
        new(
            "moonshine-tiny-streaming-en",
            "Moonshine",
            "Moonshine V2 Tiny",
            "Fastest English-only model for lightweight hardware.",
            "moonshine-tiny-streaming-en",
            "https://blob.handy.computer/moonshine-tiny-streaming-en.tar.gz",
            "465addcfca9e86117415677dfdc98b21edc53537210333a3ecdb58509a80abaf",
            31,
            "Fastest",
            "Lower",
            "English only",
            false,
            false,
            false,
            true,
            "Optimized for quick local transcription."),
        new(
            "moonshine-small-streaming-en",
            "Moonshine",
            "Moonshine V2 Small",
            "Very fast English-only model with a balanced quality footprint.",
            "moonshine-small-streaming-en",
            "https://blob.handy.computer/moonshine-small-streaming-en.tar.gz",
            "dbb3e1c1832bd88a4ac712f7449a136cc2c9a18c5fe33a12ed1b7cb1cfe9cdd5",
            100,
            "Very fast",
            "Good",
            "English only",
            false,
            false,
            false,
            true,
            "Optimized for quick local transcription."),
        new(
            "moonshine-medium-streaming-en",
            "Moonshine",
            "Moonshine V2 Medium",
            "Fast English-only model with higher local accuracy.",
            "moonshine-medium-streaming-en",
            "https://blob.handy.computer/moonshine-medium-streaming-en.tar.gz",
            "07a66f3bff1c77e75a2f637e5a263928a08baae3c29c4c053fc968a9a9373d13",
            192,
            "Fast",
            "Better",
            "English only",
            false,
            false,
            false,
            true,
            "Optimized for quick local transcription."),
        new(
            "moonshine-base",
            "Moonshine",
            "Moonshine Base",
            "Very fast English-only base model with good quality on accents.",
            "moonshine-base",
            "https://blob.handy.computer/moonshine-base.tar.gz",
            "04bf6ab012cfceebd4ac7cf88c1b31d027bbdd3cd704649b692e2e935236b7e8",
            58,
            "Very fast",
            "Good",
            "English only",
            false,
            false,
            false,
            true,
            "Optimized for quick local transcription."),
        new(
            "gigaam-v3-e2e-ctc",
            "GigaAM",
            "GigaAM v3",
            "Russian local speech recognition with strong punctuation and digit handling.",
            "giga-am-v3-int8",
            "https://blob.handy.computer/giga-am-v3-int8.tar.gz",
            "d872462268430db140b69b72e0fc4b787b194c1dbe51b58de39444d55b6da45b",
            225,
            "Fast",
            "High",
            "Russian",
            false,
            false,
            false,
            true,
            "Supports punctuation, Latin characters and digits."),
        new(
            "canary-180m-flash",
            "Canary",
            "Canary 180M Flash",
            "Fast transcription and translation across English, German, Spanish and French.",
            "canary-180m-flash",
            "https://blob.handy.computer/canary-180m-flash.tar.gz",
            "e9bde5cfc013063976c45d447e57d949f69a4b787f0ef7c1850c8cd7454ad24b",
            146,
            "Fast",
            "Good",
            "4 languages",
            true,
            true,
            false,
            true,
            "Set the language manually for best transcription."),
        new(
            "canary-1b-v2",
            "Canary",
            "Canary 1B v2",
            "High-quality transcription and translation across 25 European languages.",
            "canary-1b-v2",
            "https://blob.handy.computer/canary-1b-v2.tar.gz",
            "68bc8f8fd6d3c65c9082c14f3c3e1adab4ba9166f969b8c71d12f3f6f163346a",
            692,
            "Moderate",
            "High",
            "25 languages",
            true,
            true,
            false,
            true,
            "Set the language manually for best transcription."),
        new(
            "sense-voice-int8",
            "SenseVoice",
            "SenseVoice",
            "Fastest option for Chinese, English, Japanese, Korean and Cantonese.",
            "sense-voice-int8",
            "https://blob.handy.computer/sense-voice-int8.tar.gz",
            "171d611fe5d353a50bbb741b6f3ef42559b1565685684e9aa888ef563ba3e8a4",
            160,
            "Fastest",
            "Good",
            "5 languages",
            false,
            true,
            false,
            true,
            "Best for the supported East Asian languages plus English.")
    ];

    internal static IReadOnlyList<LocalSpeechModelDefinition> GetAll()
    {
        return _models;
    }

    internal static LocalSpeechModelDefinition? GetById(string? id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            return null;
        }

        return _models.FirstOrDefault(model =>
            string.Equals(model.Id, id.Trim(), StringComparison.OrdinalIgnoreCase));
    }

    internal static LocalSpeechModelDefinition GetDefault()
    {
        return GetById(DefaultModelId) ?? _models[0];
    }

    internal static string Normalize(string? id)
    {
        return GetById(id)?.Id ?? DefaultModelId;
    }
}
